{
 "title": "Four Keys",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  {
   "title": "コミットからデプロイまでのリードタイム",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT\n day,\n IFNULL(ANY_VALUE(med_time_to_change), 0) AS median_time_to_change, # Hours\nFROM (\n SELECT\n  d.deploy_id,\n  TIMESTAMP_TRUNC(d.time_created, DAY) AS day,\n  PERCENTILE_CONT(\n  IF(TIMESTAMP_DIFF(d.time_created, c.time_created, HOUR) > 0, TIMESTAMP_DIFF(d.time_created, c.time_created, HOUR), NULL), # Ignore automated pushes\n  0.5) # Median\n  OVER (PARTITION BY TIMESTAMP_TRUNC(d.time_created, DAY)) AS med_time_to_change, # Minutes\n FROM four_keys.deployments d, d.changes\n LEFT JOIN four_keys.changes c ON changes = c.change_id\n)\nGROUP BY day\nORDER BY day"
    },
    { "expression": "60", "type": "math" }
   ]
  },
  {
   "title": "コミットからデプロイまでのリードタイム",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SElECT IFNULL(ANY_VALUE(med_time_to_change), 0) AS lead_time_to_change\nFROM (\n  SELECT\n  PERCENTILE_CONT(\n  IF(TIMESTAMP_DIFF(d.time_created, c.time_created, HOUR) > 0, TIMESTAMP_DIFF(d.time_created, c.time_created, HOUR), NULL), # Ignore automated pushes\n  0.5) # Median\n  OVER () AS med_time_to_change, # Minutes\nFROM four_keys.deployments d, d.changes\nLEFT JOIN four_keys.changes c ON changes = c.change_id\nWHERE d.time_created > TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH))\n)"
    }
   ]
  },
  {
   "title": "日毎のデプロイ回数",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 0 },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "WITH last_month AS\n(SELECT\nTIMESTAMP(day) AS day\nFROM\nUNNEST(\nGENERATE_DATE_ARRAY(\n    \"2023-05-01\", CURRENT_DATE(),\n    INTERVAL 1 DAY)) AS day\n# FROM the start of the data\nWHERE day > (SELECT date(min(time_created)) FROM four_keys.events_raw)\n)\n\nSELECT\nTIMESTAMP_TRUNC(last_month.day, WEEK) as week,\nCOUNT(distinct deployments.day) as days_deployed\nFROM last_month\nLEFT JOIN(\n  SELECT\n  TIMESTAMP_TRUNC(time_created, DAY) AS day,\n  deploy_id\n  FROM four_keys.deployments) deployments ON deployments.day = last_month.day\nGROUP BY week"
    }
   ]
  },
  {
   "title": "デプロイ頻度",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "WITH last_month AS\n(SELECT\nTIMESTAMP(day) AS day\nFROM\nUNNEST(\nGENERATE_DATE_ARRAY(\n    DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH), CURRENT_DATE(),\n    INTERVAL 1 DAY)) AS day\n# FROM the start of the data\nWHERE day > (SELECT date(min(time_created)) FROM four_keys.events_raw)\n)\n\nSELECT ROUND(COUNTIF(days_deployed >= 3)/COUNT(1) * 100) AS accomplished_week_rate\nFROM(\n    SELECT\n    TIMESTAMP_TRUNC(last_month.day, WEEK) as week,\n    COUNT(distinct deployments.day) as days_deployed\n    FROM last_month\n    LEFT JOIN(\n      SELECT\n      TIMESTAMP_TRUNC(time_created, DAY) AS day,\n      deploy_id\n      FROM four_keys.deployments) deployments ON deployments.day = last_month.day\n    GROUP BY week)"
    }
   ]
  },
  {
   "title": "不具合発生から解消までの時間の中央値",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 10 },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT\n  TIMESTAMP_TRUNC(time_created, DAY) as day,\n  #### Median time to resolve\n  PERCENTILE_CONT(\n    TIMESTAMP_DIFF(time_resolved, time_created, HOUR), 0.5)\n    OVER(PARTITION BY TIMESTAMP_TRUNC(time_created, DAY)\n    ) as daily_med_time_to_restore,\n  FROM four_keys.incidents\nORDER BY day"
    }
   ]
  },
  {
   "title": "不具合発生から修正までの時間の中央値",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT\nCASE WHEN med_time_to_resolve < 24  then \"One day\"\n     WHEN med_time_to_resolve < 168  then \"One week\"\n     WHEN med_time_to_resolve < 730  then \"One month\"\n     WHEN med_time_to_resolve < 730 * 6 then \"Six months\"\n     ELSE \"One year\"\n     END as med_time_to_resolve,\nFROM (\n  SELECT\n  #### Median time to resolve\n  PERCENTILE_CONT(\n    TIMESTAMP_DIFF(time_resolved, time_created, HOUR), 0.5)\n    OVER() as med_time_to_resolve,\n  FROM four_keys.incidents\n  # Limit to 3 months\n  WHERE time_created > TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH)))\nLIMIT 1"
    }
   ]
  },
  {
   "title": "変更失敗率",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 13, "y": 10 },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT\nTIMESTAMP_TRUNC(d.time_created, DAY) as day,\n  IF(COUNT(DISTINCT change_id) = 0,0, SUM(IF(i.incident_id is NULL, 0, 1)) / COUNT(DISTINCT deploy_id)) as change_fail_rate\nFROM four_keys.deployments d, d.changes\nLEFT JOIN four_keys.changes c ON changes = c.change_id\nLEFT JOIN(SELECT\n        DISTINCT incident_id,\n        change,\n        time_resolved\n        FROM four_keys.incidents i,\n        i.changes change) i ON i.change = changes\nGROUP BY day"
    }
   ]
  },
  {
   "title": "不具合数 / デプロイ数",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "location": "US",
     "project": "gglobo-deployment-frq-hdg-prd",
     "rawSql": "SELECT\nCASE WHEN change_fail_rate <= .15 then \"0-15%\"\n     WHEN change_fail_rate < .46 then \"16-45%\"\n     ELSE \"46-60%\" end as change_fail_rate\nFROM \n (SELECT\n    IF(COUNT(DISTINCT change_id) = 0,0, SUM(IF(i.incident_id is NULL, 0, 1)) / COUNT(DISTINCT deploy_id)) as change_fail_rate\n  FROM four_keys.deployments d, d.changes\n  LEFT JOIN four_keys.changes c ON changes = c.change_id\n  LEFT JOIN(SELECT\n          incident_id,\n          change,\n          time_resolved\n          FROM four_keys.incidents i,\n          i.changes change) i ON i.change = changes\n  # Limit to 3 months\n  WHERE d.time_created > TIMESTAMP(DATE_SUB(CURRENT_DATE(), INTERVAL 3 MONTH))\n  )\nLIMIT1"
    }
   ]
  }
 ]
}